services:
  jupyter:
    build: .
    container_name: ppgia-jupyter
    ports:
      - "8889:8888"
    volumes:
      - ./periodo_1:/app/periodo_1
      - ./periodo_2:/app/periodo_2
      - ./periodo_3:/app/periodo_3
      - ./periodo_4:/app/periodo_4
    working_dir: /app
    restart: unless-stopped
